# Generated by Django 2.1.5 on 2019-01-05 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourValue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=8, default=25.0, max_digits=20)),
                ('date', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
